/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-tertiary-container": "#bc8a00",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#004f54",
        "tertiary-container": "#3a2800",
        surface: "#f8f9ff",
        "primary-container": "#1a2b4b",
        "on-tertiary-fixed-variant": "#5d4200",
        "on-primary-fixed-variant": "#364768",
        "inverse-surface": "#213145",
        outline: "#75777f",
        "on-background": "#0b1c30",
        "secondary-container": "#7af1fc",
        "surface-tint": "#4e5e81",
        "secondary-fixed-dim": "#5dd8e2",
        primary: "#031635",
        "tertiary-fixed": "#ffdea3",
        background: "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#44474e",
        error: "#ba1a1a",
        "primary-fixed": "#d8e2ff",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#081b3a",
        "on-secondary-fixed": "#002022",
        "on-secondary-container": "#006e75",
        "outline-variant": "#c5c6cf",
        "on-tertiary-fixed": "#261900",
        "surface-bright": "#f8f9ff",
        "on-secondary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "surface-container": "#e5eeff",
        "on-primary": "#ffffff",
        "secondary-fixed": "#7df4ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#fdbc13",
        tertiary: "#201500",
        "on-primary-container": "#8293b8",
        "inverse-primary": "#b6c6ef",
        "surface-container-low": "#eff4ff",
        secondary: "#006970",
        "primary-fixed-dim": "#b6c6ef",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "title-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        headline: ["Hanken Grotesk"],
        display: ["Hanken Grotesk"],
        body: ["Hanken Grotesk"],
        label: ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
      },
      animation: {
        'slide-in': 'slideIn 0.25s ease-out',
        'fade-out': 'fadeOut 0.2s ease-in forwards',
      },
      keyframes: {
        slideIn: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
      },
    },
  },
  plugins: [],
}
