-- Permite INSERT explicito do id (como o AUTO_INCREMENT do MySQL sempre permitiu),
-- necessario para seed.js que insere utilizadores.id = 1 explicitamente.
DO $$
DECLARE
  t text;
BEGIN
  FOR t IN
    SELECT table_name FROM information_schema.columns
    WHERE table_schema = 'public' AND column_name = 'id' AND is_identity = 'YES'
  LOOP
    EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET GENERATED BY DEFAULT', t);
  END LOOP;
END $$;
