-- SIGE - Schema Postgres/Supabase
-- Porte fiel do schema MySQL (sige_db.sql + migrate_*.js + colunas usadas em backend/src
-- que nunca chegaram a ser versionadas em SQL). Ver notas de reconstrucao no fim do ficheiro.
--
-- Convencoes de traducao MySQL -> Postgres:
--   INT AUTO_INCREMENT PRIMARY KEY  -> INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--     (BY DEFAULT em vez de ALWAYS: permite INSERT explicito de id, tal como
--     o AUTO_INCREMENT do MySQL permite -- usado por ex. em seed.js)
--   TINYINT(1)                      -> SMALLINT (0/1 -- mantém compatibilidade com literais MySQL-style usados no codigo)
--   LONGTEXT / TEXT                 -> TEXT
--   JSON                            -> JSONB
--   ENUM(...)                       -> VARCHAR(n) + CHECK (col IN (...))
--   TIMESTAMP ... ON UPDATE CURRENT_TIMESTAMP -> TIMESTAMP DEFAULT CURRENT_TIMESTAMP + trigger
--   DEFAULT (CURDATE())             -> DEFAULT CURRENT_DATE
--
-- Politica de FKs: escola_id -> escolas(id) ON DELETE CASCADE em todas as tabelas (padrao
-- 100% consistente no schema original). Relacoes adicionais so foram declaradas como FK
-- quando o sige_db.sql / migrate_*.js original ja as declarava explicitamente, ou quando a
-- tabela e nova (sem DDL original) e a evidencia de uso no codigo e inequivoca. Onde havia
-- risco de dependencia circular (departamentos/funcionarios/cargos) as FKs sao adicionadas
-- no fim, via ALTER TABLE.

-- ============================================================================
-- Funcao auxiliar para colunas "ON UPDATE CURRENT_TIMESTAMP"
-- ============================================================================
CREATE OR REPLACE FUNCTION set_atualizado_em()
RETURNS TRIGGER AS $$
BEGIN
  NEW.atualizado_em = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- Nucleo (escolas, utilizadores)
-- ============================================================================

CREATE TABLE IF NOT EXISTS escolas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(200) NOT NULL,
  sigla VARCHAR(20),
  localizacao VARCHAR(300),
  provincia VARCHAR(100),
  cidade VARCHAR(100),
  contacto VARCHAR(50),
  email VARCHAR(150),
  ano_lectivo VARCHAR(10),
  nivel_ensino VARCHAR(50),
  logo VARCHAR(500),
  cor_principal VARCHAR(20) DEFAULT '#1a2b4b',
  cor_secundaria VARCHAR(20) DEFAULT '#fdbc13',
  activo SMALLINT NOT NULL DEFAULT 1,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS utilizadores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER REFERENCES escolas(id) ON DELETE SET NULL,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(150) UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('director','secretaria','professor','financeiro','rh','pedagogico','aluno','super_admin')),
  codigo VARCHAR(50),
  primeiro_login SMALLINT NOT NULL DEFAULT 1,
  data_nascimento DATE,
  aluno_id INTEGER,
  activo SMALLINT DEFAULT 1,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Estrutura academica legada (turmas) e nova (grade_levels/subjects/class_groups)
-- ============================================================================

CREATE TABLE IF NOT EXISTS turmas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(100) NOT NULL,
  classe VARCHAR(20),
  sala VARCHAR(50),
  professor_director_id INTEGER,
  ano_lectivo VARCHAR(10),
  capacidade INTEGER DEFAULT 30,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS salas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  codigo VARCHAR(50),
  nome VARCHAR(150) NOT NULL,
  tipo VARCHAR(50) NOT NULL DEFAULT 'Sala de Aula',
  capacidade INTEGER NOT NULL DEFAULT 40,
  activo SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS grade_levels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  ordem INTEGER NOT NULL,
  nivel_ensino VARCHAR(50) NOT NULL DEFAULT 'Secundário',
  activo SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS subjects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  codigo VARCHAR(50),
  grade_level_id INTEGER REFERENCES grade_levels(id) ON DELETE SET NULL,
  carga_horaria INTEGER NOT NULL DEFAULT 4,
  activo SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS class_groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  grade_level_id INTEGER NOT NULL REFERENCES grade_levels(id) ON DELETE CASCADE,
  room_id INTEGER REFERENCES salas(id) ON DELETE SET NULL,
  nome VARCHAR(100) NOT NULL,
  turno VARCHAR(20) NOT NULL DEFAULT 'Manhã',
  capacidade INTEGER NOT NULL DEFAULT 40,
  ano_lectivo VARCHAR(9),
  professor_director_id INTEGER,
  activo SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS teaching_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  professor_id INTEGER NOT NULL REFERENCES utilizadores(id) ON DELETE CASCADE,
  class_group_id INTEGER NOT NULL REFERENCES class_groups(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  ano_lectivo VARCHAR(9),
  carga_horaria INTEGER DEFAULT 4,
  activo SMALLINT NOT NULL DEFAULT 1
);

-- ============================================================================
-- Alunos, disciplinas, notas, presencas (legado)
-- ============================================================================

CREATE TABLE IF NOT EXISTS alunos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  foto TEXT,
  data_nascimento DATE,
  naturalidade VARCHAR(150),
  nacionalidade VARCHAR(100) DEFAULT 'Moçambicana',
  bi VARCHAR(50),
  telefone VARCHAR(30),
  email VARCHAR(150),
  endereco VARCHAR(300),
  curso VARCHAR(100),
  turno VARCHAR(10) CHECK (turno IN ('Manhã','Tarde','Noite')),
  ano_lectivo VARCHAR(10),
  nome_encarregado VARCHAR(150),
  tel_encarregado VARCHAR(30),
  parentesco VARCHAR(50) DEFAULT 'Pai/Mãe',
  genero VARCHAR(1) CHECK (genero IN ('M','F')),
  turma_id INTEGER REFERENCES turmas(id) ON DELETE SET NULL,
  class_group_id INTEGER,
  numero_matricula VARCHAR(50),
  status VARCHAR(20) NOT NULL DEFAULT 'activo' CHECK (status IN ('activo','inactivo','suspenso','transferido','concluido','desistente')),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS disciplinas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(100) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  disciplina_id INTEGER NOT NULL REFERENCES disciplinas(id) ON DELETE CASCADE,
  turma_id INTEGER,
  trimestre SMALLINT NOT NULL,
  tipo VARCHAR(50),
  valor DECIMAL(5,2),
  observacoes TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS presencas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  turma_id INTEGER,
  disciplina_id INTEGER,
  data DATE NOT NULL,
  professor_id INTEGER,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  presente SMALLINT DEFAULT 0,
  justificada SMALLINT DEFAULT 0,
  observacao TEXT
);

-- ============================================================================
-- Secretaria (matriculas, documentos, encarregados, transferencias, solicitacoes)
-- ============================================================================

CREATE TABLE IF NOT EXISTS aluno_matriculas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  class_group_id INTEGER NOT NULL,
  ano_lectivo VARCHAR(10) NOT NULL,
  numero_matricula VARCHAR(60),
  data_matricula DATE DEFAULT CURRENT_DATE,
  turno VARCHAR(20),
  observacoes TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'matriculado' CHECK (status IN ('pendente','matriculado','activo','cancelado')),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS aluno_documentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  tipo VARCHAR(100) NOT NULL,
  descricao TEXT,
  arquivo TEXT,
  data_doc DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','em_processamento','concluido','cancelado')),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS encarregados (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  parentesco VARCHAR(80) NOT NULL DEFAULT 'Pai/Mãe',
  telefone VARCHAR(30),
  email VARCHAR(150),
  endereco VARCHAR(300),
  profissao VARCHAR(100),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS aluno_encarregados (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  encarregado_id INTEGER NOT NULL REFERENCES encarregados(id) ON DELETE CASCADE,
  principal SMALLINT NOT NULL DEFAULT 0,
  UNIQUE (aluno_id, encarregado_id)
);

CREATE TABLE IF NOT EXISTS transferencias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  tipo VARCHAR(30) NOT NULL CHECK (tipo IN ('interna','externa_saida','externa_entrada','mudanca_turma','mudanca_curso')),
  class_group_origem_id INTEGER,
  class_group_destino_id INTEGER,
  escola_origem VARCHAR(200),
  escola_destino VARCHAR(200),
  motivo TEXT,
  data DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','aprovada','rejeitada')),
  observacoes TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS solicitacoes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  tipo VARCHAR(30) NOT NULL CHECK (tipo IN ('declaracao','historico','certificado','declaracao_matricula','declaracao_frequencia','comprovativo')),
  status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','em_processamento','concluida','cancelada')),
  observacoes TEXT,
  numero_doc VARCHAR(50),
  data_conclusao DATE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS matriculas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  turma_id INTEGER NOT NULL REFERENCES turmas(id) ON DELETE CASCADE,
  data_matricula DATE NOT NULL DEFAULT CURRENT_DATE
);

-- ============================================================================
-- Pedagogico (periodos, planos curriculares, avaliacoes, conselhos, resultados)
-- ============================================================================

CREATE TABLE IF NOT EXISTS periodos_lectivos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(100) NOT NULL,
  ano_lectivo VARCHAR(9) NOT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT '1_trimestre' CHECK (tipo IN ('1_trimestre','2_trimestre','3_trimestre','exame','recurso')),
  data_inicio DATE,
  data_fim DATE,
  nota_minima DECIMAL(4,1) NOT NULL DEFAULT 10.0,
  frequencia_minima DECIMAL(4,1) NOT NULL DEFAULT 75.0,
  status VARCHAR(10) NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto','fechado')),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (escola_id, ano_lectivo, tipo)
);

CREATE TABLE IF NOT EXISTS planos_curriculares (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  grade_level_id INTEGER NOT NULL REFERENCES grade_levels(id) ON DELETE CASCADE,
  subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  tipo VARCHAR(15) NOT NULL DEFAULT 'obrigatoria' CHECK (tipo IN ('obrigatoria','opcional')),
  carga_horaria INTEGER NOT NULL DEFAULT 4,
  ano_lectivo VARCHAR(9),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (escola_id, grade_level_id, subject_id, ano_lectivo)
);

CREATE TABLE IF NOT EXISTS avaliacoes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  tipo VARCHAR(15) NOT NULL DEFAULT 'teste' CHECK (tipo IN ('teste','prova','exame','trabalho','exercicio')),
  subject_id INTEGER REFERENCES subjects(id) ON DELETE SET NULL,
  class_group_id INTEGER REFERENCES class_groups(id) ON DELETE SET NULL,
  periodo_id INTEGER REFERENCES periodos_lectivos(id) ON DELETE SET NULL,
  peso DECIMAL(5,2) DEFAULT 100.00,
  data_programada DATE,
  status VARCHAR(10) NOT NULL DEFAULT 'activa' CHECK (status IN ('activa','fechada')),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conselhos_classe (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  class_group_id INTEGER NOT NULL REFERENCES class_groups(id) ON DELETE CASCADE,
  periodo_id INTEGER REFERENCES periodos_lectivos(id) ON DELETE SET NULL,
  data DATE,
  observacoes TEXT,
  decisoes TEXT,
  alunos_risco TEXT,
  status VARCHAR(15) NOT NULL DEFAULT 'rascunho' CHECK (status IN ('rascunho','finalizado')),
  criado_por INTEGER,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_conselhos_classe_atualizado_em BEFORE UPDATE ON conselhos_classe
  FOR EACH ROW EXECUTE FUNCTION set_atualizado_em();

CREATE TABLE IF NOT EXISTS resultados_finais (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  class_group_id INTEGER NOT NULL REFERENCES class_groups(id) ON DELETE CASCADE,
  periodo_id INTEGER NOT NULL REFERENCES periodos_lectivos(id) ON DELETE CASCADE,
  media_final DECIMAL(5,2),
  frequencia_pct DECIMAL(5,2),
  situacao VARCHAR(15) NOT NULL DEFAULT 'pendente' CHECK (situacao IN ('aprovado','reprovado','exame','recurso','pendente')),
  fechado_em TIMESTAMP,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (escola_id, aluno_id, class_group_id, periodo_id)
);

-- ============================================================================
-- Financeiro (taxas, pagamentos, cobrancas, bolsas, planos, contas, fechos)
-- ============================================================================

CREATE TABLE IF NOT EXISTS taxas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  valor DECIMAL(10,2) NOT NULL,
  classe VARCHAR(20),
  descricao TEXT,
  obrigatoria SMALLINT DEFAULT 1,
  categoria VARCHAR(20) NOT NULL DEFAULT 'academico' CHECK (categoria IN ('academico','servicos','administrativo','outro')),
  valor_variavel SMALLINT NOT NULL DEFAULT 0,
  grade_level_id INTEGER REFERENCES grade_levels(id) ON DELETE SET NULL,
  periodicidade VARCHAR(20) DEFAULT 'mensal',
  activo SMALLINT NOT NULL DEFAULT 1,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pagamentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  taxa_id INTEGER REFERENCES taxas(id) ON DELETE SET NULL,
  valor DECIMAL(10,2) NOT NULL,
  metodo VARCHAR(50),
  comprovativo_url VARCHAR(300),
  numero_comprovativo VARCHAR(100),
  referencia VARCHAR(100),
  mes_referencia VARCHAR(7),
  data_pagamento DATE,
  numero_recibo VARCHAR(50),
  estado VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (estado IN ('pendente','em_analise','confirmado','rejeitado','aprovado')),
  motivo_rejeicao TEXT,
  analisado_por INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  analisado_em TIMESTAMP,
  aprovado_por INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  aprovado_em TIMESTAMP,
  observacoes TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_pagamentos_atualizado_em BEFORE UPDATE ON pagamentos
  FOR EACH ROW EXECUTE FUNCTION set_atualizado_em();

CREATE TABLE IF NOT EXISTS cobrancas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  taxa_id INTEGER REFERENCES taxas(id) ON DELETE SET NULL,
  valor DECIMAL(12,2) NOT NULL,
  mes_referencia VARCHAR(7),
  data_vencimento DATE,
  status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','pago','vencido','cancelado','isento')),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS planos_propinas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  grade_level_id INTEGER REFERENCES grade_levels(id) ON DELETE SET NULL,
  curso VARCHAR(100),
  ano_lectivo VARCHAR(9) NOT NULL,
  valor DECIMAL(12,2) NOT NULL,
  periodicidade VARCHAR(15) NOT NULL DEFAULT 'mensal' CHECK (periodicidade IN ('mensal','trimestral','semestral','anual')),
  meses_cobrados INTEGER NOT NULL DEFAULT 10,
  descricao TEXT,
  activo SMALLINT NOT NULL DEFAULT 1,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contas_alunos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL,
  aluno_id INTEGER NOT NULL,
  ano_lectivo VARCHAR(9) NOT NULL,
  total_cobrado DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_pago DECIMAL(12,2) NOT NULL DEFAULT 0,
  saldo_devedor DECIMAL(12,2) GENERATED ALWAYS AS (total_cobrado - total_pago) STORED,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (escola_id, aluno_id, ano_lectivo)
);
CREATE TRIGGER trg_contas_alunos_atualizado_em BEFORE UPDATE ON contas_alunos
  FOR EACH ROW EXECUTE FUNCTION set_atualizado_em();

CREATE TABLE IF NOT EXISTS bolsas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  tipo VARCHAR(15) NOT NULL DEFAULT 'parcial' CHECK (tipo IN ('total','parcial','merito','familiar','outro')),
  desconto_pct DECIMAL(5,2),
  valor_fixo DECIMAL(12,2),
  motivo TEXT,
  ano_lectivo VARCHAR(9),
  status VARCHAR(15) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','aprovada','rejeitada')),
  aprovado_por INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  aprovado_em TIMESTAMP,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fechos_financeiros (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  mes_referencia VARCHAR(7) NOT NULL,
  total_recebido DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_cobrado DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_divida DECIMAL(12,2) NOT NULL DEFAULT 0,
  num_pagamentos INTEGER NOT NULL DEFAULT 0,
  num_devedores INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(10) NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto','fechado')),
  fechado_em TIMESTAMP,
  fechado_por INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  observacoes TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (escola_id, mes_referencia)
);

-- ============================================================================
-- RH (funcionarios, departamentos, cargos, contratos, ferias, faltas, folha)
-- ============================================================================

CREATE TABLE IF NOT EXISTS funcionarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  utilizador_id INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  nome VARCHAR(150) NOT NULL,
  numero_funcionario VARCHAR(50),
  foto TEXT,
  email VARCHAR(150),
  telefone VARCHAR(30),
  bi VARCHAR(50),
  nuit VARCHAR(50),
  numero_seguranca_social VARCHAR(50),
  data_nascimento DATE,
  genero VARCHAR(1) CHECK (genero IN ('M','F')),
  estado_civil VARCHAR(50),
  endereco VARCHAR(300),
  role VARCHAR(50),
  departamento VARCHAR(100),
  departamento_id INTEGER,
  cargo_id INTEGER,
  salario_base DECIMAL(10,2),
  tipo_contrato VARCHAR(50),
  data_admissao DATE,
  banco VARCHAR(100),
  conta_bancaria VARCHAR(50),
  estado VARCHAR(15) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo','inactivo','suspenso')),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS departamentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  descricao TEXT,
  responsavel_id INTEGER REFERENCES funcionarios(id) ON DELETE SET NULL,
  activo SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS cargos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  nome VARCHAR(150) NOT NULL,
  departamento_id INTEGER REFERENCES departamentos(id) ON DELETE SET NULL,
  salario_base DECIMAL(12,2),
  descricao TEXT,
  activo SMALLINT NOT NULL DEFAULT 1
);

-- Fecha o ciclo circular funcionarios <-> departamentos <-> cargos
ALTER TABLE funcionarios ADD CONSTRAINT fk_funcionarios_departamento
  FOREIGN KEY (departamento_id) REFERENCES departamentos(id) ON DELETE SET NULL;
ALTER TABLE funcionarios ADD CONSTRAINT fk_funcionarios_cargo
  FOREIGN KEY (cargo_id) REFERENCES cargos(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS contratos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  numero_contrato VARCHAR(100),
  funcionario_id INTEGER NOT NULL REFERENCES funcionarios(id) ON DELETE CASCADE,
  tipo VARCHAR(50) NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE,
  salario DECIMAL(12,2) NOT NULL,
  horas_semanais INTEGER NOT NULL DEFAULT 40,
  observacoes TEXT,
  estado VARCHAR(20) NOT NULL DEFAULT 'activo'
);

CREATE TABLE IF NOT EXISTS faltas_rh (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  funcionario_id INTEGER NOT NULL REFERENCES funcionarios(id) ON DELETE CASCADE,
  data DATE NOT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT 'injustificada',
  dias INTEGER NOT NULL DEFAULT 1,
  observacoes TEXT
);

CREATE TABLE IF NOT EXISTS ferias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  funcionario_id INTEGER NOT NULL REFERENCES funcionarios(id) ON DELETE CASCADE,
  ano INTEGER NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  dias INTEGER NOT NULL,
  observacoes TEXT,
  estado VARCHAR(20) DEFAULT 'pendente',
  aprovado_por INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS folha_pagamento (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  mes SMALLINT NOT NULL,
  ano SMALLINT NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'rascunho' CHECK (estado IN ('rascunho','processado','pago')),
  processado_por INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  total_bruto DECIMAL(12,2),
  total_liquido DECIMAL(12,2),
  total_inss DECIMAL(12,2),
  total_irps DECIMAL(12,2),
  total_funcionarios INTEGER
);

CREATE TABLE IF NOT EXISTS salarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  funcionario_id INTEGER NOT NULL REFERENCES funcionarios(id) ON DELETE CASCADE,
  folha_id INTEGER REFERENCES folha_pagamento(id) ON DELETE SET NULL,
  mes SMALLINT NOT NULL,
  ano SMALLINT NOT NULL,
  valor_bruto DECIMAL(10,2),
  bonus DECIMAL(10,2) DEFAULT 0,
  subsidio_alimentacao DECIMAL(10,2) DEFAULT 0,
  subsidio_transporte DECIMAL(10,2) DEFAULT 0,
  subsidio_habitacao DECIMAL(10,2) DEFAULT 0,
  inss_trabalhador DECIMAL(10,2),
  inss_entidade DECIMAL(10,2),
  irps DECIMAL(10,2),
  outras_deducoes DECIMAL(10,2) DEFAULT 0,
  descontos DECIMAL(10,2),
  valor_liquido DECIMAL(10,2),
  observacoes TEXT,
  estado VARCHAR(15) NOT NULL DEFAULT 'processado' CHECK (estado IN ('processado','pago')),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rh_configuracao (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL UNIQUE REFERENCES escolas(id) ON DELETE CASCADE,
  dias_uteis_mes INTEGER NOT NULL DEFAULT 22,
  inss_trabalhador DECIMAL(5,2) NOT NULL DEFAULT 3.00,
  inss_entidade DECIMAL(5,2) NOT NULL DEFAULT 4.00,
  calcular_irps SMALLINT NOT NULL DEFAULT 1,
  componentes JSONB,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_rh_configuracao_atualizado_em BEFORE UPDATE ON rh_configuracao
  FOR EACH ROW EXECUTE FUNCTION set_atualizado_em();

CREATE TABLE IF NOT EXISTS funcionario_documentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  funcionario_id INTEGER NOT NULL REFERENCES funcionarios(id) ON DELETE CASCADE,
  tipo VARCHAR(100) NOT NULL,
  nome VARCHAR(255),
  data_doc DATE,
  data_validade DATE,
  arquivo TEXT,
  observacoes TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Governanca (politicas, aprovacoes, auditoria, notificacoes)
-- ============================================================================

CREATE TABLE IF NOT EXISTS politicas_academicas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL UNIQUE REFERENCES escolas(id) ON DELETE CASCADE,
  nota_minima_aprovacao DECIMAL(4,1) DEFAULT 10,
  frequencia_minima DECIMAL(5,2) DEFAULT 75,
  escala_max INTEGER DEFAULT 20,
  nota_exame_minima DECIMAL(4,1),
  permite_recurso SMALLINT,
  nota_minima_recurso DECIMAL(4,1),
  criterio_aprovacao TEXT,
  criterio_reprovacao TEXT,
  regras_exame TEXT,
  regras_recuperacao TEXT
);

CREATE TABLE IF NOT EXISTS politicas_financeiras (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL UNIQUE REFERENCES escolas(id) ON DELETE CASCADE,
  dias_tolerancia_pagamento INTEGER DEFAULT 5,
  percentagem_multa DECIMAL(5,2) DEFAULT 2,
  max_desconto_percentagem DECIMAL(5,2) DEFAULT 20,
  max_bolsa_percentagem DECIMAL(5,2),
  regras_inadimplencia TEXT,
  politica_descontos TEXT,
  politica_bolsas TEXT,
  regras_cobranca TEXT,
  bloquear_acesso_divida SMALLINT
);

CREATE TABLE IF NOT EXISTS politicas_administrativas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL UNIQUE REFERENCES escolas(id) ON DELETE CASCADE,
  horario_abertura VARCHAR(20),
  horario_encerramento VARCHAR(20),
  dias_funcionamento VARCHAR(100),
  missao TEXT,
  visao TEXT,
  valores TEXT,
  regras_internas TEXT,
  politicas_gerais TEXT
);

CREATE TABLE IF NOT EXISTS solicitacoes_aprovacao (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  tipo VARCHAR(50) NOT NULL,
  subtipo VARCHAR(50),
  titulo VARCHAR(200) NOT NULL,
  descricao TEXT,
  dados_json JSONB,
  solicitante_id INTEGER NOT NULL REFERENCES utilizadores(id) ON DELETE CASCADE,
  estado VARCHAR(15) NOT NULL DEFAULT 'pendente' CHECK (estado IN ('pendente','aprovado','rejeitado')),
  director_observacao TEXT,
  aprovado_em TIMESTAMP,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auditoria_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  utilizador_id INTEGER REFERENCES utilizadores(id) ON DELETE SET NULL,
  utilizador_nome VARCHAR(150),
  modulo VARCHAR(50) NOT NULL,
  acao VARCHAR(100) NOT NULL,
  detalhes TEXT,
  ip_address VARCHAR(45),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notificacoes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id INTEGER NOT NULL REFERENCES escolas(id) ON DELETE CASCADE,
  utilizador_id INTEGER REFERENCES utilizadores(id) ON DELETE CASCADE,
  titulo VARCHAR(200) NOT NULL,
  mensagem TEXT,
  tipo VARCHAR(30) DEFAULT 'informativa',
  modulo VARCHAR(50),
  url VARCHAR(300),
  lida SMALLINT NOT NULL DEFAULT 0,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Nota: nao ha dados de exemplo aqui de proposito. O unico utilizador
-- pre-criado do sistema e o super_admin, semeado por backend/src/seed.js.
-- Escolas sao sempre criadas pelo super_admin via UI (POST /api/escolas).
-- ============================================================================
-- Notas de reconstrucao
-- ============================================================================
-- As seguintes tabelas/colunas NAO existem em nenhum ficheiro .sql do repositorio
-- (sige_db.sql nem migrate_*.js) e foram reconstruidas a partir do uso real no
-- codigo (backend/src/modules/**), pois a base MySQL local (XAMPP) nao tinha
-- "sige_db" criada nesta maquina no momento da migracao:
--   - Tabelas 100% novas: cobrancas, contratos, faltas_rh, grade_levels, subjects,
--     class_groups, teaching_assignments, politicas_academicas, politicas_financeiras,
--     politicas_administrativas, solicitacoes_aprovacao, auditoria_log, salas,
--     matriculas, departamentos, cargos, ferias, folha_pagamento, notificacoes.
--   - Colunas novas em tabelas ja existentes: escolas (logo, cor_principal,
--     cor_secundaria, activo), taxas (grade_level_id, periodicidade, activo),
--     pagamentos (aprovado_por, aprovado_em, numero_recibo, mes_referencia,
--     observacoes), funcionarios (utilizador_id, estado_civil, numero_funcionario,
--     foto, telefone, bi, nuit, numero_seguranca_social, data_nascimento, genero,
--     endereco, departamento_id, cargo_id, banco, conta_bancaria), salarios
--     (folha_id, bonus, subsidio_alimentacao, subsidio_transporte,
--     subsidio_habitacao, inss_trabalhador, inss_entidade, irps, outras_deducoes,
--     observacoes).
-- Onde o codigo nao provava um CHECK/ENUM explicito (ex: contratos.tipo,
-- ferias.estado), optou-se por VARCHAR livre em vez de inventar uma lista de
-- valores. Reveja o ficheiro antes de aplicar em producao.
